Created a cardano chart
santiment/helm-charts pull request #4
Opened 2018-08-23 15:32 UTC by andyfiorini

2018-08-27 15:10 UTC, valo requested changes

2018-08-27 15:10 UTC, valo commented on cardano/templates/deployment.yaml
> +          claimName: cardano-data #{{ .Values.persistence.existingClaim | default (include "stellar-node.fullname" .) }}
Please name the name of the PVC configurable. Also I don't see the definition of the PersistenceVolumeClaim. Shouldn't it be included?

2018-08-29 06:44 UTC, valo commented on cardano/templates/deployment.yaml
> +          claimName: {{ .Values.persistence.existingClaim | default (include "stellar-node.fullname" .) }}
In the common case we don’t have an existing PVC to put here. I think there should be a PVC definition as part of this chart. See 
https://github.com/santiment/helm-charts/blob/master/stellar-node/templates/pvc.yaml

2018-08-29 13:48 UTC, andyfiorini commented
Ok, I will add the pvc.yaml in another pr.  Is that ok?  

I don't know how to add a new file to this pr now.

Regards.

2018-08-30 14:13 UTC, valo commented
It should be possible to just push to your forked repo and the PR will update.

To speed up things I'll merge this one now

2018-08-30 14:13 UTC, valo approved these changes

2018-08-30 14:13 UTC, merged